######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 11 12:44:11 2015
######################################################################

TEMPLATE = app
TARGET = arping 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arp.h \
    chain.h \
    netdev.h
SOURCES += arp.c ping.c \
    chain.c \
    netdev.c
