######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 11 12:44:11 2015
######################################################################

TEMPLATE = app
TARGET = arping 
DEPENDPATH += .

# Input
HEADERS += arp.h \
    chain.h \
    netdev.h \
    frame.h \
    receiver.h
SOURCES += src/arp.c \
    src/ping.c \
    src/chain.c \
    src/netdev.c \
    src/frame.c \
    src/receiver.c
